/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as iVerifierSol from "./IVerifier.sol";
export type { iVerifierSol };
export type { GameContract } from "./GameContract";
export type { SpinContract } from "./SpinContract";
export * as factories from "./factories";
export { GameContract__factory } from "./factories/GameContract__factory";
export type { IZKVerifier } from "./IVerifier.sol/IZKVerifier";
export { IZKVerifier__factory } from "./factories/IVerifier.sol/IZKVerifier__factory";
export { SpinContract__factory } from "./factories/SpinContract__factory";
