/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface SpinContractInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "owner"
      | "setOwner"
      | "setVerifier"
      | "setVerifierImageCommitments"
      | "settleProof"
      | "verifier"
      | "zk_image_commitments"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "VerificationSucceeded"): EventFragment;

  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setOwner",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setVerifier",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setVerifierImageCommitments",
    values: [[BigNumberish, BigNumberish, BigNumberish]]
  ): string;
  encodeFunctionData(
    functionFragment: "settleProof",
    values: [BigNumberish[], BigNumberish[], BigNumberish[], BigNumberish[][]]
  ): string;
  encodeFunctionData(functionFragment: "verifier", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "zk_image_commitments",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setOwner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setVerifier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setVerifierImageCommitments",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "settleProof",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "verifier", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "zk_image_commitments",
    data: BytesLike
  ): Result;
}

export namespace VerificationSucceededEvent {
  export type InputTuple = [sender: AddressLike];
  export type OutputTuple = [sender: string];
  export interface OutputObject {
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SpinContract extends BaseContract {
  connect(runner?: ContractRunner | null): SpinContract;
  waitForDeployment(): Promise<this>;

  interface: SpinContractInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  owner: TypedContractMethod<[], [string], "view">;

  setOwner: TypedContractMethod<[new_owner: AddressLike], [void], "nonpayable">;

  setVerifier: TypedContractMethod<
    [verifier_address: AddressLike],
    [void],
    "nonpayable"
  >;

  setVerifierImageCommitments: TypedContractMethod<
    [commitments: [BigNumberish, BigNumberish, BigNumberish]],
    [void],
    "nonpayable"
  >;

  settleProof: TypedContractMethod<
    [
      proof: BigNumberish[],
      verify_instance: BigNumberish[],
      aux: BigNumberish[],
      instances: BigNumberish[][]
    ],
    [void],
    "nonpayable"
  >;

  verifier: TypedContractMethod<[], [string], "view">;

  zk_image_commitments: TypedContractMethod<
    [arg0: BigNumberish],
    [bigint],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setOwner"
  ): TypedContractMethod<[new_owner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setVerifier"
  ): TypedContractMethod<[verifier_address: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setVerifierImageCommitments"
  ): TypedContractMethod<
    [commitments: [BigNumberish, BigNumberish, BigNumberish]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "settleProof"
  ): TypedContractMethod<
    [
      proof: BigNumberish[],
      verify_instance: BigNumberish[],
      aux: BigNumberish[],
      instances: BigNumberish[][]
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "verifier"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "zk_image_commitments"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  getEvent(
    key: "VerificationSucceeded"
  ): TypedContractEvent<
    VerificationSucceededEvent.InputTuple,
    VerificationSucceededEvent.OutputTuple,
    VerificationSucceededEvent.OutputObject
  >;

  filters: {
    "VerificationSucceeded(address)": TypedContractEvent<
      VerificationSucceededEvent.InputTuple,
      VerificationSucceededEvent.OutputTuple,
      VerificationSucceededEvent.OutputObject
    >;
    VerificationSucceeded: TypedContractEvent<
      VerificationSucceededEvent.InputTuple,
      VerificationSucceededEvent.OutputTuple,
      VerificationSucceededEvent.OutputObject
    >;
  };
}
