/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as iVerifierSol from "./IVerifier.sol";
export { GameContract__factory } from "./GameContract__factory";
export { SpinContract__factory } from "./SpinContract__factory";
